### ISSUE TITLE
Minor tweaks to sim tools

### ISSUE THREAD

**Issue by piguy314159265** [alteryx/AlteryxSim#11]
**Simulation Scoring**
- [x] Change seed max from 100 to 100000000 @piguy314159265 - https://github.com/alteryx/SimScoring/pull/21

**Simulation Summary**
- [x] Create sample workflows. @piguy314159265

**Simulation Sampling**
- [x] Remove excessive warnings @piguy314159265 - https://github.com/alteryx/SimSampling/pull/25
- [x] Better error checking on bounds and parameters. @piguy314159265 (partially done)
- [x] Remove rouletteData text input. @ramnathv
- [x] Tests for distribution fitting. @piguy314159265 - https://github.com/alteryx/SimSampling/pull/23
- [x] Tests for replacement/non-replacement. @ramnathv - Done in 1 tool
- [x] Tests for chunking. @piguy314159265 - https://github.com/alteryx/SimSampling/pull/23
- [x] Write metadata for use downstream. @piguy314159265 + @ramnathv
- [x] Remove null rows @piguy314159265 - https://github.com/alteryx/SimSampling/pull/23

**All**
- [x] Remove all diagnostic print statements from workflows - @piguy314159265 - https://github.com/alteryx/SimSampling/pull/25

**Post Code Freeze**
- [ ] Write regression tests for all simulation tools.
- [ ] Error message for missing id/val binned data (not sure possible) - @piguy314159265
- [ ] Make bounds distribution specific. @ramnathv  (was this you? yes)
- [ ] Better error messaging. (actually pretty good already) @piguy314159265
- [ ] Better reporting. @ramnathv (later)

**Comment by ramnathv** [comment]
__Simulation Scoring__

- [ ]  Write regression tests.

__Simulation Summary__

- [ ] Better reporting.
- [ ] Write regression tests.
- [ ] Create sample workflows.

__Simulation Sampling__

- [ ] Tests for distribution fitting.
- [ ] Tests for replacement/non-replacement.
- [ ] Tests for chunking.
- [ ] Make bounds distribution specific.
- [ ] Better error checking on bounds and parameters.
- [ ] Better error messaging.
- [ ] Write metadata for use downstream.

**Comment by piguy314159265** [comment]
Dist fitting: https://github.com/piguy314159265/SimSampling/commit/476e2da64ee6c90a101464fe64ca7e3795b9f64c

**Comment by piguy314159265** [comment]
https://github.com/alteryx/AlteryxSim/commit/2f1d0371fc69c6c66f8de9706bc9a5d398ce5bfc I'm really lost on how to fix this. It was only error-throwing for pareto

**Comment by piguy314159265** [comment]
I'm having trouble getting git to add my Sim Summary sample.

**Comment by piguy314159265** [comment]
Suggestion for remaining priorities:
__@piguy314159265__
Essentials (All SimSampling)
- Remove excessive warnings 

Nice (All SimSampling)
- Better error checking on bounds and parameters.  (partially done)
- Error message for missing id/val binned data (not sure possible)
- Better error messaging. (actually pretty good already) 

__@ramnathv__ 
Essentials 
- SimSampling: Remove rouletteData text input.
- Remove all diagnostic print statements

Nice
- SimSampling: Make bounds distribution specific.
- SimSummary: Improve Reporting

**Comment by ramnathv** [comment]
I am closing this issue for now. We will most likely review this tool again to figure out next steps on what tweaks we need to make.
